### ISSUE TITLE
ver.4.0.0.3β

### ISSUE THREAD

**Issue by s-kikko** [hibara/AttacheCase4#1]
①常に選択する暗号化ファイルのタイプ
　[オプション] - [保存]の常に選択する暗号化ファイルとタイプにパスワードZIPが残ったままになっています。
　(公開鍵暗号に変わっていないだけかと)

②暗号化ファイルタイプの切り替え
　パスワード入力画面で暗号化タイプのアイコンクリックで暗号化ファイルの切り替えできますが、こちらも
　パスワードZIPになっています。
　選択すると公開鍵暗号に変わるので、アイコンの問題だけかと思われます。

③暗号強度
　暗号化したいファイルをドロップし、パスワードを入力する際に表示される暗号強度が機能していません。
　「Somewhat weak」となっており、マルが灰色のままです。

④予期せぬエラー
　「アプリケーションのコンポーネントで、ハンドルされていない例外が発生しました。」が発生します。
　発生パターンは以下のとおり。

　(1)暗号化したいファイルをドロップし、パスワードを入力し、OKで再度パスワード入力の画面に進まずに
　　戻るアイコン(←)またはキャンセルボタンで戻る。
　(2)パスワードを入力せずにOKで再度パスワード入力の画面に進み、戻るアイコンまたはキャンセルボタン
　　で戻る。
　(3)暗号化ファイルを作成する。(暗号化ファイルは出来上がります)
　(4)[ファイル]-[暗号化する]-[ファイルの選択]または[フォルダの選択]で暗号化したいファイル(フォルダ)を
　　選択する。

⑤パスワードなし暗号化のブロック依頼(暗号化時のパスワード入力必須化)
　暗号化時にパスワードを必須入力としていただけますようお願いいたします。
　パスワードを入力しない(パスワードなし)で暗号化してしまうと、復号できなくなってしまいます。

お忙しいところ申し訳ございませんが、ご確認いただけると幸いです。

**Comment by hibara** [comment]
詳細なご報告ありがとうございます。

> ①常に選択する暗号化ファイルのタイプ

アイコンとして残っているだけではなく、機能としてもおかしく、きちんと切り替わることができなかったので、公開鍵暗号の項目を増やしつつ、修正いたしました。

> ②暗号化ファイルタイプの切り替え

アイコンだけ差し替えれば良いという問題だけでなく、通常暗号へ飛んでしまっていました。こちらも公開鍵暗号機能へ飛ぶようにしつつ、修正を施しました。

> ③暗号強度

暗号強度メーターですが、内部的にライブラリを更新した際に、強度メーターに使うファイル（zxcvbn.dll）が取り込まれていなかったようです。ですので、判定が行われず常にエラーを返していた状態でした。こちらも修正いたしました。

> ④予期せぬエラー

なかなかに盛大で致命的なバグでした。おそらく、上記のライブラリ脱落の関係で不安定になっていたのだと思います。デバッグモードで動作させているときは問題なかったので、油断しておりました。こちらも、③と合わせて修正が施されております。

> ⑤パスワードなし暗号化のブロック依頼(暗号化時のパスワード入力必須化)

こちらはバグ、というより、仕様として禁止しておいた方が安全という意味でしょうか？　現状、空白にしても問題なく、暗号化・復号は行われています。

この問題に関しては、以前から何度か要望やご意見をいただきますが、自由度の高さを優先させています。もし必須化というのであれば、デフォルトは空白をNGにして、設定でチェックオフすることで空白をO.K.にするという感じでしょうか？

なお、これら⑤以外、修正されたものは、以下からダウンロードできます。お試しいただければと思います。

[https://hibara.org/software/attachecase/](https://hibara.org/software/attachecase/)

**Comment by s-kikko** [comment]
早速のご対応ありがとうございます。

> ①常に選択する暗号化ファイルのタイプ

直っているのを確認しました。
ただ、日本語でも「Public key cryptography」となっているので少し気になりました。

> ⑤パスワードなし暗号化のブロック依頼(暗号化時のパスワード入力必須化)
> こちらはバグ、というより、仕様として禁止しておいた方が安全という意味でしょうか？　現状、空白にしても問題なく、暗号化・復号は行われています。

申し訳ございません。私の確認不足ですので、取り下げます。
動作確認した際に、(適当なファイルで良かったのですが)暗号化するファイルを用意するのが面倒だったので、新規作成で空ファイル(0バイト)のテキストファイルを暗号化していました。
その際にパスワードなしで暗号化したら復号出来なくなってしまったので、あげさせていただきました。
今試すと、パスワードありでも復号できませんでした。
どうも、0バイトファイルを暗号化すると復号出来なくなってしまうようです。
(幾つかのファイルをフォルダに入れて、そのフォルダを暗号化した場合でも、1つでも0バイトのファイルが混じっているとNGのようです)
普通に考えて、0バイトのファイルを暗号化することはないと思います。

**Comment by hibara** [comment]
> ただ、日本語でも「Public key cryptography」となっているので少し気になりました。

たしかに、ここの日本語化を忘れておりました。修正しました。

> 動作確認した際に、(適当なファイルで良かったのですが)暗号化するファイルを用意するのが面倒だったので、新規作成で空ファイル(0バイト)のテキストファイルを暗号化していました。

過去にけっこう苦労したバグで、こちらでも再現しました。先祖返りバグですね。さらに厄介なことに、ある条件下で0バイトファイルが含まれると、復号できないことにもなっていました。こちらも合わせて修正しました。

すでに公式サイトにて、ver.4.0.0.5βとして公開しておりますので、よろしければお試しいただければと思います。

**Comment by s-kikko** [comment]
早速のご対応ありがとうございます。
> たしかに、ここの日本語化を忘れておりました。修正しました。

リソースファイルに反映されていないようで、日本語でも「Public key cryptography」のままでした。
(gitのソースもなので更新漏れかと思います)

> 過去にけっこう苦労したバグで、こちらでも再現しました。先祖返りバグですね。さらに厄介なことに、ある条件下で0バイトファイルが含まれると、復号できないことにもなっていました。こちらも合わせて修正しました。

余計なことをしてしまったようで、すみません。
ver.4.0.0.5βを私の環境で確認すると奇妙なことになっています。

①「atc」形式で暗号化した場合
　0バイトファイルも0バイト以外のファイルも正常に復号されますが、DeveloperConsoleが開きます。

②「exe」形式で暗号化した場合
　0バイトのファイルを暗号化後、正しいパスワードで復号すると「パスワードがちがうか～」とエラーになりますが、0バイトのファイルが出来ています。(復号はされる)

お手数をおかけいたしますが、ご確認いただけると幸いです。

**Comment by hibara** [comment]
毎回丁寧なご報告ありがとうございます。とても助かります。

> ①「atc」形式で暗号化した場合
> 　0バイトファイルも0バイト以外のファイルも正常に復号されますが、DeveloperConsoleが開きます。

こちらは再現できませんでした・・・設定パネルからチェックボックスをOFFにして様子を見てみていただけますでしょうか。

> ②「exe」形式で暗号化した場合
>　0バイトのファイルを暗号化後、正しいパスワードで復号すると「パスワードがちがうか～」とエラーになりますが、0バイトのファイルが出来ています。(復号はされる)

これはまさに盲点でした。こちらも同様のソースコードを使い回しており、同じ問題を抱えていました。
たいへん助かりました。

さっそく②のみの修正を行ったものを更新し、ver.4.0.0.6βとして公開いたしました。よろしければお試しいただければと思います。

**Comment by s-kikko** [comment]
> こちらは再現できませんでした・・・設定パネルからチェックボックスをOFFにして様子を見てみていただけますでしょうか。

申し訳ございません。開発モードを見落としておりました。
設定にある開発モードのチェックがONになっていたのが原因のようです。

②「exe」形式で暗号化は改善されていることを確認しました。
迅速な対応ありがとうございます。
