### ISSUE TITLE
複数ファイルを暗号化しようとすると「ハンドルされていない例外が発生した」とエラーが出る

### ISSUE THREAD

**Issue by satoguma** [hibara/AttacheCase4#3]
複数ファイルを暗号化しようとして、アタッシュケースにドロップすると以下のエラーが出現します。
1つ目の暗号化ファイルはできていますが、2つ目以降は作成されずにエラー表示となります。

OS：Windows11 Pro 21H2（クリーンインストール）
アタッシュケースバージョン：4.0.2.5

![エラー画面](https://user-images.githubusercontent.com/95002513/143329585-a7deb149-f408-4e51-8ef9-68ab14b09813.jpg)

【詳細】
Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

************** 例外テキスト **************
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 AttacheCase.Form1.backgroundWorker_Encryption_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   場所 System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** 読み込まれたアセンブリ **************
mscorlib
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4420.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AttacheCase
    アセンブリ バージョン:4.0.2.5
    Win32 バージョン:4.0.2.5
    コードベース:file:///C:/Program%20Files%20(x86)/AttacheCase4/AttacheCase.exe
----------------------------------------
System.Windows.Forms
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4400.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4360.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4395.0 built by: NET48REL1LAST_B
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4395.0 built by: NET48REL1LAST_B
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml.Linq
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4161.0 built by: NET48REL1
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4161.0 built by: NET48REL1
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4341.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
AttacheCase.resources
    アセンブリ バージョン:4.0.2.5
    Win32 バージョン:4.0.2.5
    コードベース:file:///C:/Program%20Files%20(x86)/AttacheCase4/AttacheCase.exe
----------------------------------------
AttacheCase.resources
    アセンブリ バージョン:4.0.2.5
    Win32 バージョン:4.0.2.5
    コードベース:file:///C:/Program%20Files%20(x86)/AttacheCase4/AttacheCase.exe
----------------------------------------
System.Windows.Forms.resources
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4161.0 built by: NET48REL1
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Zxcvbn
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:4.0.2.5
    コードベース:file:///C:/Program%20Files%20(x86)/AttacheCase4/AttacheCase.exe
----------------------------------------
Accessibility
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4161.0 built by: NET48REL1
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.VisualBasic
    アセンブリ バージョン:10.0.0.0
    Win32 バージョン:14.8.4161.0 built by: NET48REL1
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
mscorlib.resources
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4161.0 built by: NET48REL1
    コードベース:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT デバッグ **************
Just-In-Time (JIT) デバッグを有効にするには、このアプリケーション、
またはコンピューター (machine.config) の構成ファイルの jitDebugging 
値を system.windows.forms セクションで設定しなければなりません。
アプリケーションはまた、デバッグを有効にしてコンパイルされなければ
なりません。

例:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT デバッグが有効なときは、このダイアログ ボックスで処理するよりも、
ハンドルされていない例外はすべてコンピューターに登録された
JIT デバッガーに設定されなければなりません。

**Comment by hibara** [comment]
ご報告ありがとうございます。

調査したところ、前のバージョンの修正において、余計な処理を追加してしまっていたせいで起きていた問題のようです（具体的には、暗号化処理終了後に自動的に暗号化オブジェクトを初期化してしまっていた）。

その問題を修正したものを以下に公開いたしましたので、よろしければお試しいただければと思います。

ver.4.0.2.6
https://hibara.org/software/attachecase/
