### ISSUE TITLE
特定のディスプレイを利用している際に起動直後にクラッシュする

### ISSUE THREAD

**Issue by lf-uraku-yuki** [hibara/AttacheCase4#4]
お世話になっております。
特定のディスプレイを利用している際に
アタッシェケース4 が起動直後にクラッシュする現象を確認しました。
（アタッシェケース3でも同様に再現します）

スタートメニューから起動を行うと
ディスプレイ全体を覆うサイズでボタンなどが何もないウィンドウが表示され、
2秒ほどでクラッシュします。

環境:
利用バージョン: ver.4.2.3.0
PC: モバイルPC (ASUS ROG Ally)
OS: Windows 11 22H2 
　すべてのWindowsUpdateを適用済み
ディスプレイドライババージョン: 22.40.58.04-230614a-392778C-Asus

内臓ディスプレイを利用: フルHD解像度、スケーリング100%設定
　→現象が発生する。
HDMI接続のディスプレイを利用: フルHD解像度、スケーリング100%設定
　→現象が発生しない。

試した事（いずれも解決せず）:
・内臓ディスプレイスケーリングの変更
・内臓ディスプレイのHDR無効化
・内臓ディスプレイのリフレッシュレート変更
・.netFrameworkの再インストール試行

イベントログ:
アプリケーション:AttacheCase.exe
フレームワークのバージョン:v4.0.30319
説明: ハンドルされない例外のため、プロセスが中止されました。
例外情報:System.NullReferenceException
   場所 AttacheCase.AppSettings.DetectFileType()
   場所 AttacheCase.Form1.panelDecrtpt_VisibleChanged(System.Object, System.EventArgs)
   場所 System.Windows.Forms.Control.OnVisibleChanged(System.EventArgs)
   場所 System.Windows.Forms.Control.OnParentVisibleChanged(System.EventArgs)
   場所 System.Windows.Forms.Control.OnVisibleChanged(System.EventArgs)
   場所 System.Windows.Forms.Control.OnParentVisibleChanged(System.EventArgs)
   場所 System.Windows.Forms.Control.OnVisibleChanged(System.EventArgs)
   場所 System.Windows.Forms.Form.OnVisibleChanged(System.EventArgs)
   場所 System.Windows.Forms.Control.SetVisibleCore(Boolean)
   場所 System.Windows.Forms.Form.SetVisibleCore(Boolean)
   場所 System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   場所 System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   場所 AttacheCase.Program.Main()

障害が発生しているアプリケーション名: AttacheCase.exe、バージョン: 4.2.3.0、タイム スタンプ: 0x64081627
障害が発生しているモジュール名: unknown、バージョン: 0.0.0.0、タイム スタンプ: 0x00000000
例外コード: 0xc0000005
障害オフセット: 0x00007ff81aab2bc4
障害が発生しているプロセス ID: 0x0x4D44
障害が発生しているアプリケーションの開始時刻: 0x0x1D9B57A62691936
障害が発生しているアプリケーション パス: C:\Program Files (x86)\AttacheCase4\AttacheCase.exe
障害が発生しているモジュール パス: unknown
レポート ID: 87788fda-56b4-4510-a57d-80f95822e837
障害が発生しているパッケージの完全な名前: 

環境固有の問題である可能性もありますが
上記、報告させていただきます。

**Comment by hibara** [comment]
ご報告ありがとうございます！
ちょうど私も、`ASUS ROG`シリーズのゲーミングノートPCで開発しておりますが、問題が出たことはありません。。。

ちょっと気になるのが、貼り付けていただいたエラーログを見ると、暗号化ファイルかどうかを判定している箇所で例外エラーが発生しているようです（表面上は復号処理が呼ばれているように見えます）。

ただ、これがモニターが変更すると起きるというのが、どうしても原因として結びつかず、困惑しております。

いったん、モニターの種類については脇に置いておいて、修正方向としては、初回起動時に復号画面への遷移・表示を制限する方向で修正を加えてみようと思います。これで回避できるかもしれません。

**Comment by hibara** [comment]
他のユーザー様からご報告いただき、どうやらWindows機（Windows11）がタブレットモードで動作するときに、発生する不具合だと分かりました。おそらくお使いのモバイルPCもタブレットモードで動作しているのではないでしょうか？　別モニターに接続させるとタッチできなくなり、タブレットモードではなくなるので、不具合は発生しなくなります。

実際に、不具合の確認、及びその修正と、動作確認は終わりましたので、他のバグ修正も完了次第、アップデートを公開したいと思います。

いましばらくお待ちください。

**Comment by lf-uraku-yuki** [comment]
利用しているPCがタッチ操作に対応していますので、おそらくその状態だったものと思われます。
ご対応いただきありがとうございます。とても助かります。

**Comment by hibara** [comment]
時間がかかってすみません。先ほど、その「タブレットモード」に対応した最新版のアタッシェケースをアップデートして公開しました。お試しいただければと思います。

アタッシェケース　ver.4.2.4.0
https://hibara.org/software/attachecase/

**Comment by lf-uraku-yuki** [comment]
無事解決いたしました。ご対応いただきありがとうございました。
