### ISSUE TITLE
古いOSで作ったファイルの復号ができない現象

### ISSUE THREAD

**Issue by shige1234567890** [hibara/AttacheCase4#5]
お世話になっております。
古いOSで作ったファイルの復号ができない現象が発生しました。

Windows 8.1　アタッシェケースver.4.2.2.0を使って暗号化

Windows 11 Home　バージョン：22H2　OSビルド：22621.2428
アタッシェケースver.4.2.3.0を使って復号

復号中に「予期せぬエラーが発生しました。処理を中止します。」と出て復号が中断します。
<img width="274" alt="image" src="https://github.com/hibara/AttacheCase4/assets/149885138/ad33aa0e-8a58-4a57-b5a1-1bcf7df37218">

手元に古いOSがないため再現ができないのですがご確認いただければ幸いです。
新しいOSでアタッシェケースver.4.2.2.0を使って復号を試みましたが同様のエラーが発生しました。

**Comment by hibara** [comment]
ご報告ありがとうございます。お時間をいただいて申し訳ありません。

Windows8.1を入手し、同じ状況のもので任意のファイルを替えながら何回か、暗号化し、Windows11へ持ってきて復号しましたが、問題は再現いたしませんでした・・・すべて問題なく復号できました。

暗号化ツールというセンシティブなデータを扱う上で、難しいかもしれませんが、もし再現できるデータをいただければ、こちらで何が起きているか追うことができます。

可能なら再現データをいただければ幸いです。

**Comment by hibara** [comment]
ご提供いただいたデータにより、内部で暗号化前に取ったハッシュ値と、復号後のファイルのハッシュ値が異なるため、「ファイルが破損した」と判断して、エラーとなっていたようです。

しかし、今回のようにデータが破損していないようにも思えることがあったため、今後はハッシュ値エラーが出た際は、ユーザーに復号処理を続行するか否かという問い合わせを行うことで対処することにしました。

この不具合を修正したものを以下の場所に公開しました。ご利用くださればと思います。

アタッシェケース　ver.4.2.4.0
https://hibara.org/software/attachecase/

**Comment by shige1234567890** [comment]
ご連絡ありがとうございます。
新しいバージョンで無事に復号ができました。
ありがとうございました。
